name: Build DMG
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (macOS only)
        run: |
          rustup target add aarch64-apple-darwin

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target universal-apple-darwin

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: DotDash-DMG-${{ github.sha }}
          path: src-tauri/target/universal-apple-darwin/release/bundle/dmg/*.dmg
          retention-days: 30